[package]
name = "ethtool"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://kernel.org/pub/software/network/ethtool/"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-6.5.tar.xz"
sha512 = "07994a20f34b1c1e72f9f855972d31d027968b53b278a5b46c5a2977be8d7152e6439c9719001101be85359876d9d932d2afb9561af9967e84d8a447a7d0c558"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
