[package]
name = "aws-iam-authenticator"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes-sigs/aws-iam-authenticator/archive/v0.5.5/aws-iam-authenticator-0.5.5.tar.gz"
sha512 = "24c2a7fd141f921e18c17f4c7e90bbf5325cc6fad3b35753c0da2d879cf64d8f6af0130f8c45ec7693d6fce043181abbd04a911e6fa778f686bd5c313631ed0f"

[build-dependencies]
glibc = { path = "../glibc" }
