[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_18"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.18"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.18.18/kubernetes-1.18.18.tar.gz"
sha512 = "8305cff40d08a40c6c8e71e9056fac6b76856a6e39ac8d2e3952c155a8c70a9d7c269725d55df180dd906d0ff6d9c8b9e17a58b00a08c86438f1435058163fd3"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
conntrack-tools = { path = "../conntrack-tools" }
# `containerd` and `findutils` are only needed at runtime, and are pulled in by
# `release`.
# containerd = { path = "../containerd" }
# findutils = { path = "../findutils" }
