[package]
name = "hotdog"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bottlerocket-os/hotdog/archive/v1.0.5/hotdog-1.0.5.tar.gz"
sha512 = "6bd4d2701b51e27cf39ef4fca5573d7343c1dc9def299f7f19deadb37cc38f5dc2576e54475c972ff2b590ed3293af4ca9a39eb4d202aec1be49e8c74cf52d29"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }

[dependencies]
log4j2-hotpatch= { path = "../log4j2-hotpatch" }
