[package]
name = "apiclient"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
datastore = { path = "../datastore" }
futures = { version = "0.3", default-features = false }
http = "0.2"
hyper = { version = "0.13", default-features = false }
hyper-unix-connector = "0.1"
# when we update hyper to 0.14+ and tokio to 1
# hyper-unix-connector = "0.2"
log = "0.4"
models = { path = "../../models" }
rand = "0.8"
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.9"
snafu = { version = "0.6", features = ["futures"] }
tokio = { version = "0.2", default-features = false, features = ["fs", "macros", "rt-threaded", "time"] }
# When we update hyper to 0.14+ which has tokio 1:
#tokio = { version = "1", default-features = false, features = ["fs", "macros", "rt-multi-thread", "time"] }
toml = "0.5"
unindent = "0.1"
url = "2.2.1"

[build-dependencies]
cargo-readme = "3.1"
