[package]
name = "apiclient"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
constants = { path = "../../constants", version = "0.1.0" }
datastore = { path = "../datastore", version = "0.1.0" }
futures = { version = "0.3", default-features = false }
http = "0.2"
# Ensure we use exactly hyper 0.14.2 which is the last version that does not emit a cdylib
# See this issue for tracking https://github.com/bottlerocket-os/bottlerocket/issues/1471
hyper = { version = "=0.14.2", default-features = false, features = [ "client", "http1", "http2" ] }
hyper-unix-connector = "0.2"
log = "0.4"
models = { path = "../../models", version = "0.1.0" }
rand = "0.8"
reqwest = { version = "0.11.1", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.10"
snafu = { version = "0.6", features = ["futures"] }
tokio = { version = "~1.8", default-features = false, features = ["fs", "io-std", "macros", "rt-multi-thread", "time"] }  # LTS
toml = "0.5"
unindent = "0.1"
url = "2.2.1"

[build-dependencies]
cargo-readme = "3.1"
