schema-version = 1

[sdk]
registry = "public.ecr.aws/bottlerocket"
name = "bottlerocket-sdk"
version = "v0.35.0"

[toolchain]
registry = "public.ecr.aws/bottlerocket"
name = "bottlerocket-toolchain"
version = "v0.35.0"
