[package]
name = "ca-certificates"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://curl.se/docs/caextract.html"

[[package.metadata.build-package.external-files]]
url = "https://curl.haxx.se/ca/cacert-2022-03-18.pem"
sha512 = "ef82868c7d0ea1ff708a4f63cd8f10158384931f39ba2300bbf1ffcc3ff3fea2282f8f78cf74a78d0b93d83297e2cfcabb7427a463d3199087b708b624aabc42"
