[package]
name = "coreutils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/coreutils"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.0.tar.xz"
sha512 = "9be08212891dbf48e5b22e7689dc27dac50df4631ebf29313470b72b7921f0b2aa5242917d05587785358495ca56e3b21f5b3ca81043d53cab92354da6c53a03"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
