[package]
name = "policycoreutils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/SELinuxProject/selinux/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/3.3/policycoreutils-3.3.tar.gz"
sha512 = "db658990355f99a8e43f53d20cc67bf9e557b0a7837d1927c80f325b7f93ad47876382278a980b818484d6e31712a9b03e279f947ebc88c4be60a9f395607f98"

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
libsemanage = { path = "../libsemanage" }
libsepol = { path = "../libsepol" }
