[package]
name = "dbus-broker"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bus1/dbus-broker/releases/download/v28/dbus-broker-28.tar.xz"
sha512 = "81a05a3ad2fbc0292a7de0cc719c5946e2d70d0bf91abb2eb9764fdef738a460a0cc988e050d0985ff45009a51677df3f619f4e17c8712df34c85e84826efbee"

[build-dependencies]
glibc = { path = "../glibc" }
libexpat = { path = "../libexpat" }
libselinux = { path = "../libselinux" }
systemd = { path = "../systemd" }
