[package]
name = "dbus-broker"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/bus1/dbus-broker/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bus1/dbus-broker/releases/download/v32/dbus-broker-32.tar.xz"
sha512 = "aa23d058771f56e6378df0a17ac413813b6350b77e61128c0887f35a546f10534b1a6d598868e9f5c642244c3632a8ce5e315e6794305a56f5abbebd36bf822c"

[build-dependencies]
glibc = { path = "../glibc" }
libexpat = { path = "../libexpat" }
libselinux = { path = "../libselinux" }
systemd = { path = "../systemd" }
