[package]
name = "libnetfilter_conntrack"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnetfilter_conntrack/files"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_conntrack/files/libnetfilter_conntrack-1.0.8.tar.bz2"
sha512 = "ddc70e7e3f2d764ed1e115e4a03fe8848b8c04bd69eea0952e63131dd4dae3c23f33b8be518673e1ec3b5dbf708f5f86eac97be46fe265d95386a5e902bd0b82"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnfnetlink = { path = "../libnfnetlink" }
