[package]
name = "docker-proxy"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/libnetwork/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/libnetwork/archive/f7cdd0e7adbf0818e384178093aa67e38ffdb112/libnetwork-f7cdd0e7adbf0818e384178093aa67e38ffdb112.tar.gz"
sha512 = "45e2acdd3cd059e6b1cc670b30e3d68b274e04b7c056ba031e0476c605b9264827defc280b20e09a339afcf853a83aae93e2fb28931df8b13dcd151a6a4da74c"

[build-dependencies]
glibc = { path = "../glibc" }
