[package]
name = "libpcre"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://ftp.pcre.org/pub/pcre/pcre2-10.35.tar.bz2"
sha512 = "ecfb8d48e219daff02874783b7b436fe7d70d8471e44eb66e1e29abb7b0aa67547e6b5fba7058b074ac90eef265ece7d12728f80afdda45b6b8124435f4561fd"

[build-dependencies]
glibc = { path = "../glibc" }
