[package]
name = "makedumpfile"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/makedumpfile/makedumpfile/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/makedumpfile/makedumpfile/archive/1.7.1/makedumpfile-1.7.1.tar.gz"
sha512 = "93e36487b71f567d3685b151459806cf36017e52bf3ee68dd448382b279a422d1a8abef72e291ccb8206f2149ccd08ba484ec0027d1caab3fa1edbc3d28c3632"

[build-dependencies]
glibc = { path = "../glibc" }
libelf = { path = "../libelf" }
libz = { path = "../libz" }
libbzip2 = { path = "../libbzip2" }
