[package]
name = "kexec-tools"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://kernel.org/pub/linux/utils/kernel/kexec"

[[package.metadata.build-package.external-files]]
url = "https://kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.25.tar.xz"
sha512 = "6fd3fe11d428c5bb2ce318744146e03ddf752cc77632064bdd7418ef3ad355ad2e2db212d68a5bc73554d78f786901beb42d72bd62e2a4dae34fb224b667ec6b"

[build-dependencies]
glibc = { path = "../glibc" }
