[package]
name = "kexec-tools"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://kernel.org/pub/linux/utils/kernel/kexec"

[[package.metadata.build-package.external-files]]
url = "https://kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.23.tar.xz"
sha512 = "b6e3b967cacc31c434b185d25da4d53c822ae4bbcec26ef9d6cb171f294fdcc80913d381e686a0a41e025187835f4dc088052ff88efe75a021d7624c8b1a1ed8"

[build-dependencies]
glibc = { path = "../glibc" }
