[package]
name = "glibc"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/glibc"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.36.tar.xz"
sha512 = "9ea0bbda32f83a85b7da0c34f169607fb8a102f0a11a914e6bf531be47d1bef4f5307128286cffa1e2dc5879f0e6ccaef527dd353486883fa332a0b44bde8b3e"
