[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"
# Changelog can be found here: https://sites.google.com/site/fullycapable/release-notes-for-libcap

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.64.tar.gz"
sha512 = "628ba25c2736e5fe6469c3e1d9b28855f5d2e7e75c91d5d46cc0c01e539f3cccd00356937acffde518eb83f55e5d6124eefd53199aba705fedd520982db48652"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
