[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://sites.google.com/site/fullycapable/release-notes-for-libcap"

[[package.metadata.build-package.external-files]]
url = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.63.tar.gz"
sha512 = "0db42bc9079c75b539fd7511531a2088ba37f8d4fe75799606976a3f36bc240c4b7c87402c4b71b9c455daed098a3ddaa31687d70ed45168d471df131e2898f1"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
