[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.49.tar.gz"
sha512 = "0f0bcf1e52cb9c326634bb804b79c5f1bd82c043b0ed1d59ab6e22e0b33380d28f717c4b7ec7e0f53c02041676f48a926e510c7a22b8a1961723ba3de22792a5"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
