[package]
name = "storewolf"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiserver = { path = "../apiserver" }
bottlerocket-release = { path = "../../bottlerocket-release" }
log = "0.4"
models = { path = "../../models" }
rand = { version = "0.7", default-features = false, features = ["std"] }
semver = "0.9"
simplelog = "0.7"
snafu = "0.6"
toml = "0.5"

[build-dependencies]
cargo-readme = "3.1"

[[bin]]
name = "storewolf"
path = "src/main.rs"

[lib]
name = "storewolf"
path = "src/lib.rs"
