[workspace]
members = [
    "api/apiserver",
    "api/apiclient",
    "api/bootstrap-containers",
    "api/bork",
    "api/certdog",
    "api/corndog",
    "api/datastore",
    "api/early-boot-config",
    "api/ecs-settings-applier",
    "api/netdog",
    "api/sundog",
    "api/schnauzer",
    "api/pluto",
    "api/servicedog",
    "api/host-containers",
    "api/static-pods",
    "api/storewolf",
    "api/thar-be-settings",
    "api/thar-be-updates",
    "api/settings-committer",
    "api/migration/migrator",
    "api/migration/migration-helpers",
    "api/shibaken",

    # "api/migration/migrations/vX.Y.Z/..."
    "api/migration/migrations/v1.2.1/etc-hosts-service",
    "api/migration/migrations/v1.2.1/hostname-affects-etc-hosts",

    "bottlerocket-release",

    "imdsclient",

    "ghostdog",

    "growpart",

    "prairiedog",

    "metricdog",

    "logdog",

    "models",

    "parse-datetime",

    "updater/block-party",
    "updater/signpost",
    "updater/update_metadata",
    "updater/updog",

    "webpki-roots-shim",

    "constants"
]

[profile.release]
debug = true

# This replaces webpki-roots with a shim that reads from the ca-certificates package. See
# webpki-roots-shim/Cargo.toml for more information about using the right version number.
[patch.crates-io.webpki-roots]
path = "webpki-roots-shim"
