[package]
name = "liblzma"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://tukaani.org/xz"

[[package.metadata.build-package.external-files]]
url = "https://tukaani.org/xz/xz-5.2.6.tar.xz"
sha512 = "5c69a492227c0ff72836d7a87e6372dc2e62bedfffb33f057263e28a6341825cef67834a863ed6ac02c5368c86da89f8affbe767f8bb914064cfa478f653e935"

[build-dependencies]
glibc = { path = "../glibc" }
