[package]
name = "liblzma"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://tukaani.org/xz"

[[package.metadata.build-package.external-files]]
url = "https://tukaani.org/xz/xz-5.2.9.tar.xz"
sha512 = "fa844d63ceedf3b35c38f82532dc3b847543ac37b9e56db774c234af73d1385a300ba1033154689059031f18793d791c8cdb65bbeb031691d837f76e673372a7"

[build-dependencies]
glibc = { path = "../glibc" }
