[package]
name = "binutils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/binutils/binutils-2.35.2.tar.xz"
sha512 = "9974ede5978d32e0d68fef23da48fa00bd06b0bff7ec45b00ca075c126d6bbe0cf2defc03ecc3f17bc6cc85b64271a13009c4049d7ba17de26e84e3a6e2c0348"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
