[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

# ECS agent
[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.51.0/amazon-ecs-agent-v1.51.0.tar.gz"
sha512 = "355c6ddc157266e13dfd4665670612cd2983bcdaa7598c12203361ff7987937a18b4c4448a0e94dfa7bfe3a4f4699bc5b8c8dcb22da1c18f6f0f7be86c4a6dae"

# TODO: Package the CNI plugins
# The ECS agent repository includes two CNI plugins as git submodules.  git
# archive does not include submodules, so the tarball above does not include
# the source of those plugins.

[build-dependencies]
glibc = { path = "../glibc" }
