[package]
name = "strace"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://strace.io/files"

[[package.metadata.build-package.external-files]]
url = "https://strace.io/files/6.5/strace-6.5.tar.xz"
sha512 = "7edf7b00b5ad91be2df4e44b63df7f88376f3e6a8f078dfccf307a6a5003ad25d9cf233f2a32139e00fe399494ce6a8f67728bf9dfeb9bb5958ed08ce25e9e01"

[build-dependencies]
glibc = { path = "../glibc" }
