[package]
name = "nvidia-k8s-device-plugin"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/k8s-device-plugin/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/k8s-device-plugin/archive/v0.12.3/v0.12.3.tar.gz"
sha512 = "38d75cd972ba3b8bf0c656ad179392ddaec1ac47dc595b3c9f0409bbeaea788e40170d0015cd249772860a73c479f0b23292e0538bcc316299f05ae5a24e4477"

[build-dependencies]
glibc = { path = "../glibc" }
