[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/besser82/libxcrypt/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/archive/v4.4.27/libxcrypt-4.4.27.tar.gz"
sha512 = "83b5854ca4b928522b8f4bf865331a50e3ffb3c873727e406a87a96408398c00cb617f68224c3413ed976d8060aa60bdea730e0fc8b0321a163d0b4ec496ce10"

[build-dependencies]
glibc = { path = "../glibc" }
