[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/besser82/libxcrypt/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/archive/v4.4.26/libxcrypt-4.4.26.tar.gz"
sha512 = "fd58e397c59fd8f227a0006ed1039ef1d89e033f792f186a8c352fddc0741616fabe9784eb081aecac4db945741dd730f6cef36e6354f252fd934ce0866fdb2a"

[build-dependencies]
glibc = { path = "../glibc" }
