[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/besser82/libxcrypt/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/archive/v4.4.31/libxcrypt-4.4.31.tar.gz"
sha512 = "b8a9d4d08d62af9ed8632f257467366e28635ffdcace9409b465e2a1506b7920c43d935827e50c948c62ec9919f73b14a3077a7b5ca998f3a2a6d8a2aa5fbd17"

[build-dependencies]
glibc = { path = "../glibc" }
