[package]
name = "grep"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.kernel.org/gnu/grep"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.kernel.org/gnu/grep/grep-3.7.tar.xz"
sha512 = "e9e45dcd40af8367f819f2b93c5e1b4e98a251a9aa251841fa67a875380fae52cfa27c68c6dbdd6a4dde1b1017ee0f6b9833ef6dd6e419d32d71b6df5e972b82"

[dependencies]
libpcre = { path = "../libpcre" }

[build-dependencies]
libpcre = { path = "../libpcre" }
glibc = { path = "../glibc" }
