[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/moby/moby/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v20.10.12/moby-20.10.12.tar.gz"
sha512 = "f4122c8cbc67e6b7703856dc76d6f15d7fab1b2001d4916b89958d5319c16d8b8445881841ef4804e8d47d64694184aec1be93e22d7baceb021c4a99c2c03753"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }

# RPM Requires
[dependencies]
# `containerd`, `iptables`, and `procps` are only needed at runtime, and are
# pulled in by `release`.
# containerd = { path = "../containerd" }
# iptables = { path = "../iptables" }
# procps = { path = "../procps" }
