[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/moby/moby/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v20.10.16/moby-20.10.16.tar.gz"
sha512 = "5fdf87f98a951af87a334a5a403e36b975ff6c4647d0656dde2bd763d27562c620346f3746adafa1439c205869c721a3bef750f8302734499423ca789218f85d"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }

# RPM Requires
[dependencies]
# `containerd`, `iptables`, and `procps` are only needed at runtime, and are
# pulled in by `release`.
# containerd = { path = "../containerd" }
# iptables = { path = "../iptables" }
# procps = { path = "../procps" }
