[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/moby/moby/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v20.10.18/moby-20.10.18.tar.gz"
sha512 = "202f9f4d455329907e87bd95549aa433b6c773d3067cc89d0bd2e087bddfc66faddd6c2019843e42bf3fed6d6584ba4ab61d762f436f8bb164aa11e6280c91c5"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }

# RPM Requires
[dependencies]
# `containerd`, `iptables`, and `procps` are only needed at runtime, and are
# pulled in by `release`.
# containerd = { path = "../containerd" }
# iptables = { path = "../iptables" }
# procps = { path = "../procps" }
