[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/moby/moby/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v20.10.11/moby-20.10.11.tar.gz"
sha512 = "ac947e882abb02d52aea4aecb5dcfef6e23c86aadf98b49e3312ca3079dac7a01d6c936c0a4e51b3561def926ae50b4c5587063b8c58cac5c5de3c5e7985b120"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }

# RPM Requires
[dependencies]
# `containerd`, `iptables`, and `procps` are only needed at runtime, and are
# pulled in by `release`.
# containerd = { path = "../containerd" }
# iptables = { path = "../iptables" }
# procps = { path = "../procps" }
