[package]
name = "libglib"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://download.gnome.org/sources/glib"

[[package.metadata.build-package.external-files]]
url = "https://download.gnome.org/sources/glib/2.78/glib-2.78.0.tar.xz"
sha512 = "3d06890002f4b13f831c83fbb70cfce529f9750e30888619e4d6277116be15d106379a03143412cf4b2a289c0cbdbbc299ecf17284fbffc06c791ecf7556c765"

[build-dependencies]
glibc = { path = "../glibc" }
libffi = { path = "../libffi" }
libpcre = { path = "../libpcre" }
libselinux = { path = "../libselinux" }
libz = { path = "../libz" }
util-linux = { path = "../util-linux" }
