[package]
name = "libexpat"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/libexpat/libexpat/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/libexpat/libexpat/releases/download/R_2_4_7/expat-2.4.7.tar.xz"
sha512 = "e1a16cd48fcd6c4974dc7058d2e0284e0f91565835ec93f16d3f2c79647124470e5edb9f88f1ab9df5f403883a527750a4d63b941bd26fd43c05cd6f42bdcc48"

[build-dependencies]
glibc = { path = "../glibc" }
