[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v20.10.7/cli-20.10.7.tar.gz"
sha512 = "4523ae70cb27d848da119070171af2eb84e974ac39d70be4feee105e37c949487c7f72a9bc30c32ce71bffb0787e27b7b9194ce5a8aeae57bdfeb3f2d730010f"

[build-dependencies]
glibc = { path = "../glibc" }
