[package]
name = "open-vm-tools"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/vmware/open-vm-tools/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/vmware/open-vm-tools/releases/download/stable-12.3.5/open-vm-tools-12.3.5-22544099.tar.gz"
sha512 = "7a81d929ea4871b8af0af0fa3dc62a821ac4286235255103f1bcf014e3b04b5bbbfa178a9328a16d67cfd595c4ce726dc9e195adbe21ec5c68a4d1abb1561ff6"

[build-dependencies]
glibc = { path = "../glibc" }
libglib = { path = "../libglib" }
libtirpc = { path = "../libtirpc" }
libxcrypt = { path = "../libxcrypt" }
