[package]
name = "open-vm-tools"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/vmware/open-vm-tools/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/vmware/open-vm-tools/releases/download/stable-12.3.0/open-vm-tools-12.3.0-22234872.tar.gz"
sha512 = "942be3c225d5724e236959dc0d422358b99d2844ed8f1c2d2ca06ea5959c12b1a5ac4fa47ee48c27d1c1291f6d783d1cf87303bf64b8117fd96f226ae4d632e5"

[build-dependencies]
glibc = { path = "../glibc" }
libglib = { path = "../libglib" }
libtirpc = { path = "../libtirpc" }
libxcrypt = { path = "../libxcrypt" }
