[package]
name = "open-vm-tools"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/vmware/open-vm-tools/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/vmware/open-vm-tools/releases/download/stable-12.1.0/open-vm-tools-12.1.0-20219665.tar.gz"
sha512 = "00cd71a5fc25d854d0043b2ddfb7f759e3b3138acb9f33f7452641d7520e46bfa39ff784bde6c711de6e8aec24309720532100d7a8588fb1bebaa378b9566a2a"

[build-dependencies]
glibc = { path = "../glibc" }
libglib = { path = "../libglib" }
libtirpc = { path = "../libtirpc" }
libxcrypt = { path = "../libxcrypt" }
