[package]
name = "runc"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/opencontainers/runc/archive/ff819c7e9184c13b7c2607fe6c30ae19403a7aff/runc-ff819c7e9184c13b7c2607fe6c30ae19403a7aff.tar.gz"
sha512 = "a777e0a2e8c6c9dbb507e1f4aed4092503f6b508647fd11eb58e1fbede273a5f6d3f57c71162f841e340dc3608275f499383581990ccf47a6ffd709bad23ed8c"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
