[package]
name = "runc"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/opencontainers/runc/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.tar.xz"
path = "runc-v1.1.4.tar.xz"
sha512 = "73f7b266a2aaabf180bf99d04e96a171ef12cc3c3ff43189caff324f1e4ac127a646c3c15489801d48291d997de4c88384ae957a8af4a96b3e779bcb09bc58ac"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
