[package]
name = "readline"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/readline"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/readline/readline-8.1.2.tar.gz"
sha512 = "b512275c8aa8b3b3178366c6d681f867676fc1c881e375134a88e9c860a448535e04ca43df727817fd0048261e48203e88bd1c086e86572022d1d65fb0350e4d"

[build-dependencies]
glibc = { path = "../glibc" }
libncurses = { path = "../libncurses" }
