[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_17"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.17"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.17.9/kubernetes-1.17.9.tar.gz"
sha512 = "c6c1c27a534b5b6dbbc3be34d9f8f321b0289e9032ad11549e1f028cd4cf6ba288cdc54283f5263b5e9cef017d535db911b5f7e5cbaccd2bee7d955ce2039696"

# This is a large patch, so we don't want to check it into the repo.  It's like
# https://github.com/kubernetes/kubernetes/commit/a94346bef9806a135ebcfda03672966c336c1c17
# but applies to 1.17.x without further context changes.
[[package.metadata.build-package.external-files]]
path = "aws-sdk-go-1.28.2_k8s-1.17.8.patch.bz2"
url = "file:///aws-sdk-go-1.28.2_k8s-1.17.8.patch.bz2"
sha512 = "bb98ec01b9e0aa843b8a33bf753277ff323f88061a00bc18404a488231fc6cc39208ad43b9c39338bb0a4f1e1b2751d6a2e71f86240d8694bf711a6a531f74d1"

[build-dependencies]
glibc = { path = "../glibc" }
