[package]
name = "iputils"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/iputils/iputils/releases"

[[package.metadata.build-package.external-files]]
path = "iputils-20211215.tar.gz"
url = "https://github.com/iputils/iputils/archive/20211215.tar.gz"
sha512 = "191062e51f7c8e8b38e3e4a96845adb77cd69f487d548c7cc578fad544443b4bc0dbe965d8f8e6fbda0a2f5b2fe2829789c05f873190c53d773245959298f6e9"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
