# The following represents an "accelerated" set of update waves for a much
# quicker deployment. The deployment lasts for 1 day, and quickly increases the
# nodes updated at once.
[[waves]]
start_after = '1 hour'
fleet_percentage = 3

[[waves]]
start_after = '4 hours'
fleet_percentage = 12

[[waves]]
start_after = '8 hours'
fleet_percentage = 50

[[waves]]
start_after = '1 day'
fleet_percentage = 100
