[package]
name = "certdog"
version = "0.1.0"
authors = ["Arnaldo Garcia Rincon <agarrcia@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
argh = "0.1.3"
base64 = "0.13"
constants = { path = "../../constants" }
# x509-parser depends on der-parser ^5.0.  5.1.1 contains breaking changes.
# The 5.1.1 release isn't in the master branch; those changes are instead in a
# 6.0.0 release, more clearly implying breaking changes.  Lock to 5.1.0.
der-parser = "=5.1.0"
http = "0.2"
log = "0.4"
models = { path = "../../models" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.10"
snafu = "0.6"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }
x509-parser = "0.9.2"

[dev-dependencies]
tempfile = "3.2.0"

[build-dependencies]
cargo-readme = "3.1"
