[package]
name = "chrony"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://download.tuxfamily.org/chrony"

[[package.metadata.build-package.external-files]]
url = "https://download.tuxfamily.org/chrony/chrony-4.2.tar.gz"
sha512 = "7f946b27de605b3ebea62cf23916dfad77c99e8b2338ba239ede6b8216ce436b3d4d87770f371c8d8e006507c51d5c831b51f067957abd2935adfdec3f5aa67d"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
ncurses = { path = "../ncurses" }
readline = { path = "../readline" }
