[package]
name = "libdbus"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://dbus.freedesktop.org/releases/dbus"

[[package.metadata.build-package.external-files]]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.12.22.tar.gz"
sha512 = "0a716022f9d693fcaf871b6dfb5f242b49a8dd05d3316ec3e530f5129f1d81a2fa9caec795fa62cfdcba6ed21549fdd2f896f9bf1cc9a96e2a7d04f2c7ec7be6"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libexpat = { path = "../libexpat" }
