[package]
name = "libdbus"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://dbus.freedesktop.org/releases/dbus"

[[package.metadata.build-package.external-files]]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.15.0.tar.xz"
sha512 = "6f7e1d4ff525ce13c5f671f1b045a089c379cbfb777662ce7a55ffe4893a8ab2aaf38877a7b8f261823067a20f3b336437449eb353a97d30699496375e00bf1a"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libexpat = { path = "../libexpat" }
