[package]
name = "systemd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/systemd/systemd-stable/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/systemd/systemd-stable/archive/v247.10/systemd-stable-247.10.tar.gz"
sha512 = "5f8acf8aaa190e7d8e0acf3060cdf7d52133e67529946b989d1c0df058af73f606391a5da0bcd68586f8c018b52e0ca1013ff554757ee10392fd25b8bd0cad12"

[build-dependencies]
glibc = { path = "../glibc" }
kmod = { path = "../kmod" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
util-linux = { path = "../util-linux" }
