[package]
name = "systemd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/systemd/systemd-stable/archive/v247.7/systemd-stable-247.7.tar.gz"
sha512 = "749420285eb06487a251beee4df4b91a6ab2b327f58cc9448378880abc4b5deaca301f0746f61e04355dce0408f982260c43968fae1b8ba66f4c4adac878c824"

[build-dependencies]
glibc = { path = "../glibc" }
kmod = { path = "../kmod" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
util-linux = { path = "../util-linux" }
