[package]
name = "systemd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/systemd/systemd-stable/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/systemd/systemd-stable/archive/v247.9/systemd-stable-247.9.tar.gz"
sha512 = "61cd36bec931a3550c9d25abd86d12b031d55cebf3c31eb08805947484aa93d215e3d12227cd41131a26c2a6024a74b1fef5cd4929e6240f916279bfbfc67116"

[build-dependencies]
glibc = { path = "../glibc" }
kmod = { path = "../kmod" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
util-linux = { path = "../util-linux" }
