[package]
name = "cni"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containernetworking/cni/archive/v0.8.0/cni-0.8.0.tar.gz"
sha512 = "2b0baa5be5a8b4b886c821fb03d8a186b30afd1165d6c9ea6b876a0e93a5f54375ea5cf774dbdfcc648bab05ca368add59cea2c0e1c7a7f4f4bbb9634fed6280"

[build-dependencies]
glibc = { path = "../glibc" }
