[package]
name = "libaudit"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-audit/audit-userspace/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-audit/audit-userspace/archive/v3.0.7/audit-userspace-3.0.7.tar.gz"
sha512 = "1582fada809f83fb89ed6baedd3bc51a67c88ce9cc2dc041ec51c5da89855b14c080cc6dffa1310c96f894cc2ac8b5e709fb4577d0dc9536f28a9617138db405"

[build-dependencies]
glibc = { path = "../glibc" }
