[package]
name = "libaudit"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-audit/audit-userspace/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-audit/audit-userspace/archive/v3.0.5/audit-userspace-3.0.5.tar.gz"
sha512 = "df37176e698e57ab997b9af17f00e1b5ee7b8d6afaaf792bc67d12b655700e6518aea3f6ed9fc85cc374583fd5309a3bb026e518ac02eb1f9b5ea6d9937dee3d"

[build-dependencies]
glibc = { path = "../glibc" }
