[package]
name = "libaudit"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-audit/audit-userspace/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-audit/audit-userspace/archive/v3.0.8/audit-userspace-3.0.8.tar.gz"
sha512 = "494edfb358350fc3117614a95cd8855751896e05d92fe9efb93e1582f9ded02e5f17f359328c973afc4200b00dc0d482eb5b1c25c5fc7d440184f71e055ed3ef"

[build-dependencies]
glibc = { path = "../glibc" }
