[package]
name = "libtirpc"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://sourceforge.net/projects/libtirpc/files/libtirpc/"

[[package.metadata.build-package.external-files]]
url = "https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2"
sha512 = "004e61b5853717324790c46cda5ff227d525909f189194ae72a1ec8f476ca35d7f4c1f03c0fbc690c1696d60a212675b09246dbe627fdbf1a9a47f5664e82b00"

[build-dependencies]
glibc = { path = "../glibc" }
