[package]
name = "iptables"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "http://www.netfilter.org/projects/iptables/files"

[[package.metadata.build-package.external-files]]
url = "http://www.netfilter.org/projects/iptables/files/iptables-1.8.8.tar.bz2"
sha512 = "f21df23279a77531a23f3fcb1b8f0f8ec0c726bda236dd0e33af74b06753baff6ce3f26fb9fcceb6fada560656ba901e68fc6452eb840ac1b206bc4654950f59"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnetfilter_conntrack = { path = "../libnetfilter_conntrack" }
libnfnetlink = { path = "../libnfnetlink" }
libnftnl = { path = "../libnftnl" }
