[package]
name = "iptables"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "http://www.netfilter.org/projects/iptables/files/iptables-1.8.5.tar.bz2"
sha512 = "6a6baa541bb7aa331b176e0a91894e0766859814b59e77c71351ac34d6ebd337487981db48c70e476a48c67bcf891cfc663221a7582feb1496ad1df56eb28da8"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnetfilter_conntrack = { path = "../libnetfilter_conntrack" }
libnfnetlink = { path = "../libnfnetlink" }
libnftnl = { path = "../libnftnl" }
