[package]
name = "aws-signing-helper"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/aws/rolesanywhere-credential-helper/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/rolesanywhere-credential-helper/archive/v1.1.1/rolesanywhere-credential-helper-v1.1.1.tar.gz"
sha512 = "c60d62f8e946955d181577d1e2e5fe2ecb7a82ef0c4cc29fa98b6136b93e9bac9a91cffe3a98c063d7a3f07a956b02e1dd5a92160648b26bbee90aec52a15dca"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
