[package]
name = "libsemanage"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/SELinuxProject/selinux/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/3.3/libsemanage-3.3.tar.gz"
sha512 = "6026d9773c0886436ad801bc0c8beac888b6fb62034edeb863192dea4b6ef34a88e080758820fe635a20e048ac666beee505a0f946258f18571709cca5228aad"

[build-dependencies]
glibc = { path = "../glibc" }
libaudit = { path = "../libaudit" }
libbzip2 = { path = "../libbzip2" }
libselinux = { path = "../libselinux" }
libsepol = { path = "../libsepol" }
