[package]
name = "containerd"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containerd/containerd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.6.24/containerd-1.6.24.tar.gz"
sha512 = "4c434514e5f0002063a254b89fb8ad06c7bd7a3a83954b0538367a2a343de51ca63113c384c53719127907e70c12fbcd36687b0adc737b1e42bee9f08505dee7"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
runc = { path = "../runc" }
pigz = { path = "../pigz" }
