[package]
name = "containerd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containerd/containerd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.6.6/containerd-1.6.6.tar.gz"
sha512 = "f16f23384dbaa67075f2d35b7fc752938dd15601bbe3a919bc8eaa53fa1b2dea2e2d7f613a0f2f492910213dc2f7e96f0a1d38dde35bfb6d15f18167313f9817"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
runc = { path = "../runc" }
