[package]
name = "containerd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containerd/containerd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.5.8/containerd-1.5.8.tar.gz"
sha512 = "c769506ff6d98689c46ffee94d70ae00ef2f32e0daac1e631cbe8a587f67c7e4f83eb3895707362bdf46198b61823c99df1d8ca61095ab1415de5596f106fd07"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
runc = { path = "../runc" }
