[package]
name = "libffi"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/libffi/libffi/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/libffi/libffi/releases/download/v3.4.3/libffi-3.4.3.tar.gz"
sha512 = "6e3620d3842ae0f983c47c3268364be32b6eeb2fc708b23d141531730e9149abb035c618b295be834999eadef64fabfa39df21c955c40473f3bbc9fd3170bad8"

[build-dependencies]
glibc = { path = "../glibc" }
