[package]
name = "libz"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://www.zlib.net"

[[package.metadata.build-package.external-files]]
url = "https://www.zlib.net/zlib-1.2.12.tar.xz"
sha512 = "12940e81e988f7661da52fa20bdc333314ae86a621fdb748804a20840b065a1d6d984430f2d41f3a057de0effc6ff9bcf42f9ee9510b88219085f59cbbd082bd"

[build-dependencies]
glibc = { path = "../glibc" }
