[package]
name = "util-linux"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://www.kernel.org/pub/linux/utils/util-linux"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.4.tar.xz"
sha512 = "ada2629b0a8e83ea83513e04f7b1ccceb3b8ab82acd119c5d8389d1abc48c92d0b591f39fb34b1fd65db3ab630f03a672a9f3dacf1a6e4f124bdb083fc1be6d7"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
ncurses = { path = "../ncurses" }
