[package]
name = "util-linux"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://www.kernel.org/pub/linux/utils/util-linux"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.1.tar.xz"
sha512 = "ec300c830869e10a0d7f8c0b99e9bb46e0b88fc51f3c6c6a4d9752a89f035e8d69d81f25fd103ef8d7d253e81440695ef3f5d72dccc94815ec8d5f6f949f7555"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
ncurses = { path = "../ncurses" }
