[package]
name = "release"
version = "0.0.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

# RPM BuildRequires
[build-dependencies]
# None

# RPM Requires
[dependencies]
acpid = { path = "../acpid" }
ca-certificates = { path = "../ca-certificates" }
chrony = { path = "../chrony" }
containerd = { path = "../containerd" }
coreutils = { path = "../coreutils" }
dbus-broker = { path = "../dbus-broker" }
e2fsprogs = { path = "../e2fsprogs" }
filesystem = { path = "../filesystem" }
glibc = { path = "../glibc" }
grep = { path = "../grep" }
grub = { path = "../grub" }
host-ctr = { path = "../host-ctr" }
iproute = { path = "../iproute" }
libaudit = { path = "../libaudit" }
libgcc = { path = "../libgcc" }
libstd-rust = { path = "../libstd-rust" }
os = { path = "../os" }
policycoreutils = { path = "../policycoreutils" }
selinux-policy = { path = "../selinux-policy" }
systemd = { path = "../systemd" }
util-linux = { path = "../util-linux" }
wicked = { path = "../wicked" }
