[package]
name = "libselinux"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/20200710/libselinux-3.1.tar.gz"
sha512 = "57730cddd2d4751556d9e1f207c0f85119c81848f0620c16239e997150989e3f9a586a8c23861fd51ed89f7e084ad441190a58a288258a49a95f7beef7dbbb13"

[build-dependencies]
glibc = { path = "../glibc" }
libpcre = { path = "../libpcre" }
libsepol = { path = "../libsepol" }
