[package]
name = "libselinux"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/SELinuxProject/selinux/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/3.3/libselinux-3.3.tar.gz"
sha512 = "9a89c05ea4b17453168a985ece93ba6d6c4127916e657c46d4135eb59a1f6408faa0802cc2e49187defbde5247d659037beee089877affbab3eab6af3433696c"

[build-dependencies]
glibc = { path = "../glibc" }
libpcre = { path = "../libpcre" }
libsepol = { path = "../libsepol" }
