[package]
name = "settings-committer"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
constants = { path = "../../constants" }
snafu = "0.6"
http = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.10"
tokio = { version = "~1.8", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
cargo-readme = "3.1"
