[package]
name = "nvidia-container-toolkit"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/nvidia-container-toolkit/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/nvidia-container-toolkit/archive/v1.11.0/nvidia-container-toolkit-1.11.0.tar.gz"
sha512 = "97420dc51a25e088ff9bd581c0b81a18df63a7fcf344c85a1bedecd7e897741a74e3f8aab0ad15c6035c3263c3f3d53118a941bbbeb3cf887a36aedcff3bcf80"

[build-dependencies]
glibc = { path = "../glibc" }
libnvidia-container = { path = "../libnvidia-container" }
# This package depends on `shimpei`, but it is built in the `os` package
# which is expected to be pulled in
# os = { path = "../os" }
