[package]
# This is the aws-k8s-1.16 variant.  "." is not allowed in crate names, but we
# don't use this crate name anywhere.
name = "aws-k8s-1_16"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0",
]
included-packages = [
    "aws-iam-authenticator",
    "cni",
    "cni-plugins",
    "kernel-5.4",
    "kubelet-1.16",
    "release",
]

[lib]
path = "lib.rs"

[build-dependencies]
aws-iam-authenticator = { path = "../../packages/aws-iam-authenticator" }
cni = { path = "../../packages/cni" }
cni-plugins = { path = "../../packages/cni-plugins" }
kernel-5_4 = { path = "../../packages/kernel-5.4" }
kubernetes-1_16 = { path = "../../packages/kubernetes-1.16" }
release = { path = "../../packages/release" }
