[package]
name = "libnftnl"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnftnl/files"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnftnl/files/libnftnl-1.2.3.tar.bz2"
sha512 = "e2d16cbc062eb8900f0472abb8fe6b22910cc5a8efbb47445fe6ce6e2713a0637f74b46b2bf2031ba9ecb2e5eed932e3bbb49b015c7b7207591249de23d5149d"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
