[package]
name = "libnftnl"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "http://netfilter.org/projects/libnftnl/files"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnftnl/files/libnftnl-1.2.1.tar.bz2"
sha512 = "cabe6896210c451d7917d1abde5e73a65594d53f011486f75dd7be5b4804c49d10f0e508675e091e1faf0363b82670b3f3a167a85db91d52742dc69445888b6a"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
