[package]
name = "os"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = true
source-groups = [
    "api",
    "bottlerocket-release",
    "metricdog",
    "parse-datetime",
    "ghostdog",
    "growpart",
    "updater",
    "webpki-roots-shim",
    "logdog",
    "models",
    "imdsclient"
]

[lib]
path = "pkg.rs"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# We depend on `host-ctr` for host containers functionality, but only need it
# at runtime, and expect it to be pulled in by way of the `release` package.
# host-ctr = { path = "../host-ctr" }
