[package]
name = "libzstd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/facebook/zstd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/facebook/zstd/archive/v1.5.2.tar.gz"
sha512 = "e107508a41fca50845cc2494e64adaba93efb95a2fa486fc962510a8ba4b2180d93067cae9870f119e88e5e8b28a046bc2240b0b23cdd8933d1fb1a6a9668c1e"

[build-dependencies]
glibc = { path = "../glibc" }
