[package]
name = "libzstd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/facebook/zstd/archive/v1.5.0.tar.gz"
sha512 = "25b657529a698eec891f92ff4a085d1fd95d2ff938ce52c8a4ff6163eb0b668ec642dd09e0db190652638cd92371006afa01d8e437437762c4097ad301675c33"

[build-dependencies]
glibc = { path = "../glibc" }
